"""create first Buzz schema

Revision ID: 395f45b4c409
Revises: 
Create Date: 2026-08-22 12:43:33.244787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '395f45b4c409'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buses',
    sa.Column('bus_id', sa.Uuid(), nullable=False),
    sa.Column('bus_number', sa.String(length=50), nullable=False),
    sa.Column('from_location', sa.String(length=150), nullable=False),
    sa.Column('to_location', sa.String(length=150), nullable=False),
    sa.Column('where_reached', sa.String(length=150), nullable=True),
    sa.Column('where_parked', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('bus_id'),
    sa.UniqueConstraint('bus_number')
    )
    op.create_table('departments',
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('department_id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('lecture_slots',
    sa.Column('lecture_slot_id', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('lecture_slot_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('student', 'teacher', 'admin', name='user_role'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('courses',
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.PrimaryKeyConstraint('course_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('teachers',
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('teacher_id'),
    sa.UniqueConstraint('employee_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('semesters',
    sa.Column('semester_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('semester_number', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('semester_number >= 1 AND semester_number <= 12', name='ck_semester_number'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.PrimaryKeyConstraint('semester_id'),
    sa.UniqueConstraint('course_id', 'semester_number', name='uq_course_semester')
    )
    op.create_table('teacher_daily_status',
    sa.Column('teacher_daily_status_id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('status_date', sa.Date(), nullable=False),
    sa.Column('is_available', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ),
    sa.PrimaryKeyConstraint('teacher_daily_status_id'),
    sa.UniqueConstraint('teacher_id', 'status_date', name='uq_teacher_daily_status_date')
    )
    op.create_table('teacher_departments',
    sa.Column('teacher_department_id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ),
    sa.PrimaryKeyConstraint('teacher_department_id')
    )
    op.create_table('sections',
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('semester_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.semester_id'], ),
    sa.PrimaryKeyConstraint('section_id')
    )
    op.create_table('subjects',
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('semester_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.semester_id'], ),
    sa.PrimaryKeyConstraint('subject_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('students',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('semester_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('roll_number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.section_id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.semester_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('roll_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('subject_teachers',
    sa.Column('subject_teacher_id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.section_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ),
    sa.PrimaryKeyConstraint('subject_teacher_id'),
    sa.UniqueConstraint('teacher_id', 'subject_id', 'section_id', name='uq_subject_teacher_section')
    )
    op.create_table('assignments',
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('subject_teacher_id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['subject_teacher_id'], ['subject_teachers.subject_teacher_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('attendance',
    sa.Column('attendance_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('subject_teacher_id', sa.Uuid(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('present', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.ForeignKeyConstraint(['subject_teacher_id'], ['subject_teachers.subject_teacher_id'], ),
    sa.PrimaryKeyConstraint('attendance_id')
    )
    op.create_table('documents',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('subject_teacher_id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_teacher_id'], ['subject_teachers.subject_teacher_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('timetable',
    sa.Column('timetable_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('subject_teacher_id', sa.Uuid(), nullable=False),
    sa.Column('lecture_slot_id', sa.SmallInteger(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('day_of_week >= 1 AND day_of_week <= 6', name='check_timetable_day'),
    sa.ForeignKeyConstraint(['lecture_slot_id'], ['lecture_slots.lecture_slot_id'], ),
    sa.ForeignKeyConstraint(['subject_teacher_id'], ['subject_teachers.subject_teacher_id'], ),
    sa.PrimaryKeyConstraint('timetable_id'),
    sa.UniqueConstraint('subject_teacher_id', 'lecture_slot_id', 'day_of_week', name='uq_timetable_entry')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timetable')
    op.drop_table('documents')
    op.drop_table('attendance')
    op.drop_table('assignments')
    op.drop_table('subject_teachers')
    op.drop_table('students')
    op.drop_table('subjects')
    op.drop_table('sections')
    op.drop_table('teacher_departments')
    op.drop_table('teacher_daily_status')
    op.drop_table('semesters')
    op.drop_table('teachers')
    op.drop_table('notifications')
    op.drop_table('courses')
    op.drop_table('users')
    op.drop_table('lecture_slots')
    op.drop_table('departments')
    op.drop_table('buses')
    # ### end Alembic commands ###
