"""add otp attempts

Revision ID: 61ee19cf265a
Revises: c86846de0be2
Create Date: 2026-09-02 12:51:50.069848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61ee19cf265a'
down_revision: Union[str, Sequence[str], None] = 'c86846de0be2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Otpverification', sa.Column('attempts', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Otpverification', 'attempts')
    # ### end Alembic commands ###
