"""Modified student a little bit

Revision ID: 6514ce442caa
Revises: 7900875ee0d9
Create Date: 2026-09-12 09:06:27.552969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6514ce442caa'
down_revision: Union[str, Sequence[str], None] = '7900875ee0d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('lab_group', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'lab_group')
    # ### end Alembic commands ###
