"""Chaged name fo REfresh Token To refresh_token

Revision ID: 715e987921cd
Revises: 9a1875e6ee94
Create Date: 2026-09-03 04:52:02.180950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '715e987921cd'
down_revision: Union[str, Sequence[str], None] = '9a1875e6ee94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
