"""Removed the is_used and attempts

Revision ID: c86846de0be2
Revises: 3fe088d8fb52
Create Date: 2026-08-26 19:02:14.822497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c86846de0be2'
down_revision: Union[str, Sequence[str], None] = '3fe088d8fb52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Otpverification', 'is_used')
    op.drop_column('Otpverification', 'attempts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Otpverification', sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('Otpverification', sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
