"""empty message

Revision ID: dfe3ca834040
Revises: 1aea011a1492
Create Date: 2026-09-05 04:41:59.501665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfe3ca834040'
down_revision: Union[str, Sequence[str], None] = '1aea011a1492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Otpverification', sa.Column('purpose', sa.String(), server_default='email_verification', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Otpverification', 'purpose')
    # ### end Alembic commands ###
